format = """
$custom.sys_override
$custom.telemetry
$character
"""

add_newline = false

[custom.sys_override]
command = "echo -e '\\033[1;36m+-----------------------------------------------------+\\n| [SYSTEM OVERRIDE] :: SECURE TERMINAL LINK 0x8F      |\\n| STATUS: ROOT ACCESS GRANTED | ENCRYPTION: ACTIVE    |\\n+-----------------------------------------------------+\\033[0m'"
when = "true"
shell = ["bash", "--noprofile", "--norc"]


[character]
success_symbol = "[>> ACCESS//_](bold green) "
error_symbol = "[>> ACCESS_DENIED//!](bold red) "
